name: Firebase Deploy Frontend

on:
  workflow_dispatch:
  push:
    paths:
      - '**/client/**'
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    continue-on-error: true
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v4
      - run: cd template_onion_with_mqtt/client && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: 'template_onion_with_mqtt/client'
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASVWEATHERSTATION }}
          channelId: live
          projectId: easvweatherstation
